namespace server.Enums;

public enum ComponentType : byte
{
    None = 0,
    Box2DBody = 1,
    Gravity = 2,
    Health = 3,
    Shield = 4,
    Energy = 5,
    Engine = 6,
    Level = 8,
    Inventory = 9,
    Viewport = 10,
    NameTag = 11,
    DeathTag = 12,
    ShipPart = 13,
    ParentChild = 14,
    Color = 15,
    Lifetime = 16,
    Input = 17,
    HealthRegen = 18,
    BodyDamage = 19,
    Bullet = 20,
    Collision = 21,
    Damage = 22,
    ExpReward = 23,
    SlaveOffset = 24,
    Network = 25,
    Asteroid = 26,
    Pickup = 27,
    RespawnTag = 28,
    Spawner = 29,
    Weapon = 30,
    GridPosition = 31,
    Pickable = 32,
    AsteroidBlock = 33,
    AsteroidNeighbor = 34,
    StructuralIntegrity = 35,
    StructuralCollapse = 36,
    PickableTag = 37,
    DirectionalEngine = 38,
    WeaponMount = 39,
    DirectionalShield = 40,
    Hull = 41,
    Assembly = 42,
    Effect = 43
}